#!/usr/bin/env python
# -*- coding: iso8859-1 -*-

""" xforms-python's functions to manage formbrowser objects.
"""

#    Copyright (C) 2009, 2010  Luca Lazzaroni "LukenShiro"
#    e-mail: <lukenshiro@ngi.it>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Lesser General Public License as
#    published by the Free Software Foundation, version 2.1 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU Lesser General Public License for more details.
#
#    You should have received a copy of the GNU LGPL along with this
#    program. If not, see <http://www.gnu.org/licenses/>.
#
#    See CREDITS file to read acknowledgements and thanks to XForms,
#    ctypes and other developers.

# originally generated by 'h2xml+gccxml' and 'xml2py'
# then heavily reordered and reworked

# ############################################# #
# Interface to XForms shared object libraries   #
# ############################################# #


import ctypes as cty
from xformslib import library
from xformslib import xfdata


##########################
# forms.h (formbrowser.h)
##########################

def fl_addto_formbrowser(pFlObject, pFlForm):
    """fl_addto_formbrowser(pFlObject, pFlForm)
    
    Populates a formbrowser. The form so added is appended to the list of
    forms that are already in the formbrowser. Form should be valid for the
    duration of the formbrowser and the application program should not destroy
    a form that is added to a formbrowser before deleting the form from the
    formbrowser first.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        pFlForm : pointer to xfdata.FL_FORM
            form

    Returns
    -------
        numforms : int
            total number of forms in the formbrowser

    Examples
    --------
        >>> ntotfrms = fl_addto_formbrowser(frmbrobj, newform)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_addto_formbrowser = library.cfuncproto(
        library.load_so_libforms(), "fl_addto_formbrowser",
        cty.c_int, [cty.POINTER(xfdata.FL_OBJECT),
        cty.POINTER(xfdata.FL_FORM)],
        """int fl_addto_formbrowser(FL_OBJECT * ob, FL_FORM * form)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    library.verify_flformptr_type(pFlForm)
    library.keep_elem_refs(pFlObject, pFlForm)
    retval = _fl_addto_formbrowser(pFlObject, pFlForm)
    return retval


def fl_delete_formbrowser_bynumber(pFlObject, seqnum):
    """fl_delete_formbrowser_bynumber(pFlObject, seqnum)
    
    Removes a form from the formbrowser using a sequence number, an
    integer between 1 and the number of forms in the browser. After a
    form is removed, the sequence numbers are re-adjusted so they are
    always consecutive.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        seqnum : int
            sequence number of form to be removed

    Returns
    -------
        pFlForm : pointer to xfdata.FL_FORM
            removed form, or None (on failure)

    Examples
    --------
        >>> delfrm = fl_delete_formbrowser_bynumber(frmbrobj, 2)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_delete_formbrowser_bynumber = library.cfuncproto(
        library.load_so_libforms(), "fl_delete_formbrowser_bynumber",
        cty.POINTER(xfdata.FL_FORM), [cty.POINTER(xfdata.FL_OBJECT),
        cty.c_int],
        """FL_FORM * fl_delete_formbrowser_bynumber(FL_OBJECT * ob, int
           num)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    iseqnum = library.convert_to_int(seqnum)
    library.keep_elem_refs(pFlObject, seqnum, iseqnum)
    retval = _fl_delete_formbrowser_bynumber(pFlObject, iseqnum)
    return retval


def fl_delete_formbrowser(pFlObject, pFlForm):
    """fl_delete_formbrowser(pFlObject, pFlForm)
    
    Removes a specified form from the formbrowser.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        pFlForm : pointer to xfdata.FL_FORM
            form candidate to deletion

    Returns
    -------
        numforms : int
            current (after deletion) number of forms in the formbrowser
            or -1 (on failure)

    Examples
    --------
        >>> numfrm = fl_delete_formbrowser(frmbrobj, p2ndform)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_delete_formbrowser = library.cfuncproto(
        library.load_so_libforms(), "fl_delete_formbrowser",
        cty.c_int, [cty.POINTER(xfdata.FL_OBJECT),
        cty.POINTER(xfdata.FL_FORM)],
        """int fl_delete_formbrowser(FL_OBJECT * ob,
           FL_FORM * candidate_form)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    library.verify_flformptr_type(pFlForm)
    library.keep_elem_refs(pFlObject, pFlForm)
    retval = _fl_delete_formbrowser(pFlObject, pFlForm)
    return retval


def fl_replace_formbrowser(pFlObject, seqnum, pFlForm):
    """fl_replace_formbrowser(pFlObject, seqnum, pFlForm)
    
    Replaces a form in formbrowser specified by a sequence number

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        seqnum : int
            sequence number of form to be replaced
        pFlForm : pointer to xfdata.FL_FORM
            form used as replacement

    Returns
    -------
        pFlForm : pointer to xfdata.FL_FORM
            form that has been replaced, or None (on failure)

    Examples
    --------
        >>> replfrm = fl_replace_formbrowser(frmbrobj, 4, newreplfrm)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_replace_formbrowser = library.cfuncproto(
        library.load_so_libforms(), "fl_replace_formbrowser",
        cty.POINTER(xfdata.FL_FORM), [cty.POINTER(xfdata.FL_OBJECT),
        cty.c_int, cty.POINTER(xfdata.FL_FORM)],
        """FL_FORM * fl_replace_formbrowser(FL_OBJECT * ob, int num,
           FL_FORM * form)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    iseqnum = library.convert_to_int(seqnum)
    library.verify_flformptr_type(pFlForm)
    library.keep_elem_refs(pFlObject, seqnum, pFlForm, iseqnum)
    retval = _fl_replace_formbrowser(pFlObject, iseqnum, pFlForm)
    return retval


def fl_insert_formbrowser(pFlObject, seqnum, pFlForm):
    """fl_insert_formbrowser(pFlObject, seqnum, pFlForm)
    
    Inserts a form into a formbrowser at arbitrary location.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        seqnum : int
            the sequence number before which the new form form is to be
            inserted into the formbrowser
        pFlForm : pointer to xfdata.FL_FORM
            new form to insert

    Returns
    -------
        numforms : int
            number of forms in the formbrowser, or -1 (on failure)

    Examples
    --------
        >>> frmsnum = fl_insert_formbrowser(frmbrobj, 5, pform)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_insert_formbrowser = library.cfuncproto(
        library.load_so_libforms(), "fl_insert_formbrowser",
        cty.c_int, [cty.POINTER(xfdata.FL_OBJECT), cty.c_int, \
        cty.POINTER(xfdata.FL_FORM)],
        """int fl_insert_formbrowser(FL_OBJECT * ob, int line,
           FL_FORM * new_form)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    iseqnum = library.convert_to_int(seqnum)
    library.verify_flformptr_type(pFlForm)
    library.keep_elem_refs(pFlObject, seqnum, iseqnum, pFlForm)
    retval = _fl_insert_formbrowser(pFlObject, iseqnum, pFlForm)
    return retval


def fl_get_formbrowser_area(pFlObject):
    """fl_get_formbrowser_area(pFlObject)
    
    Obtains the actual size of the form's area. The area occupied by the
    formbrowser contains the space for the scrollbars.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object

    Returns
    -------
        result : int
            1, or 0 (on failure)
        x : int
            horizontal position
        y : int
            vertical position
        w : int
            width of form's area
        h : int
            height of form's area

    Examples
    --------
        >>> exval, x, y, w, h = fl_get_formbrowser_area(frmbrobj)

    API_diversion
    ----------
        API changed from XForms, upstream was
        fl_get_formbrowser_area(pFlObject, x, y, w, h)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_get_formbrowser_area = library.cfuncproto(
        library.load_so_libforms(), "fl_get_formbrowser_area",
        cty.c_int, [cty.POINTER(xfdata.FL_OBJECT), cty.POINTER(cty.c_int),
        cty.POINTER(cty.c_int), cty.POINTER(cty.c_int), \
        cty.POINTER(cty.c_int)],
        """int fl_get_formbrowser_area(FL_OBJECT * ob, int * x, int * y,
           int * w, int * h)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    x, px = library.make_int_and_pointer()
    y, py = library.make_int_and_pointer()
    w, pw = library.make_int_and_pointer()
    h, ph = library.make_int_and_pointer()
    library.keep_elem_refs(pFlObject, x, y, w, h, px, py, pw, ph)
    retval = _fl_get_formbrowser_area(pFlObject, px, py, pw, ph)
    return retval, x.value, y.value, w.value, h.value


def fl_set_formbrowser_scroll(pFlObject, how):
    """fl_set_formbrowser_scroll(pFlObject, how)
    
    Changes the vertical scrollbar so each action of the scrollbar scrolls
    to the next forms. By default it scrolls a fixed number of pixels.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        how : int
            How it scrolls. Values (from xfdata module) FL_SMOOTH_SCROLL
            (default) or FL_JUMP_SCROLL

    Examples
    --------
        >>> fl_set_formbrowser_scroll(frmbrobj, xfdata.FL_JUMP_SCROLL)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_set_formbrowser_scroll = library.cfuncproto(
        library.load_so_libforms(), "fl_set_formbrowser_scroll",
        None, [cty.POINTER(xfdata.FL_OBJECT), cty.c_int],
        """void fl_set_formbrowser_scroll(FL_OBJECT * ob, int how)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    library.checkfatal_allowed_value_in_list(how, xfdata.FORMBRWSSCROLL_list)
    ihow = library.convert_to_int(how)
    library.keep_elem_refs(pFlObject, how, ihow)
    _fl_set_formbrowser_scroll(pFlObject, ihow)


def fl_set_formbrowser_hscrollbar(pFlObject, how):
    """fl_set_formbrowser_hscrollbar(pFlObject, how)
    
    Controls the presence of horizontal scrollbar. By default, if the size
    of the forms exceeds the size of the formbrowser, scrollbars are added
    automatically.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        how : int
            if scrollbar is added or not. Values (from xfdata module) FL_ON,
            FL_OFF, FL_AUTO

    Examples
    --------
        >>> fl_set_formbrowser_hscrollbar(frmbrobj, xfdata.FL_OFF)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_set_formbrowser_hscrollbar = library.cfuncproto(
        library.load_so_libforms(), "fl_set_formbrowser_hscrollbar",
        None, [cty.POINTER(xfdata.FL_OBJECT), cty.c_int],
        """void fl_set_formbrowser_hscrollbar(FL_OBJECT * ob, int how)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    library.checkfatal_allowed_value_in_list(how, xfdata.SCROLLBARVAL_list)
    ihow = library.convert_to_int(how)
    library.keep_elem_refs(pFlObject, how, ihow)
    _fl_set_formbrowser_hscrollbar(pFlObject, ihow)


def fl_set_formbrowser_vscrollbar(pFlObject, how):
    """fl_set_formbrowser_vscrollbar(pFlObject, how)
    
    Controls the presence of vertical scrollbar. By default, if the size of
    the forms exceeds the size of the formbrowser, scrollbars are added
    automatically

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        how : int
            if scrollbar is added or not. Values (from xfdata module) FL_ON,
            FL_OFF, FL_AUTO

    Examples
    --------
        >>> fl_set_formbrowser_vscrollbar(frmbrobj, FL_OFF)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_set_formbrowser_vscrollbar = library.cfuncproto(
        library.load_so_libforms(), "fl_set_formbrowser_vscrollbar",
        None, [cty.POINTER(xfdata.FL_OBJECT), cty.c_int],
        """void fl_set_formbrowser_vscrollbar(FL_OBJECT * ob, int how)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    library.checkfatal_allowed_value_in_list(how, xfdata.SCROLLBARVAL_list)
    ihow = library.convert_to_int(how)
    library.keep_elem_refs(pFlObject, how, ihow)
    _fl_set_formbrowser_vscrollbar(pFlObject, ihow)


def fl_get_formbrowser_topform(pFlObject):
    """fl_get_formbrowser_topform(pFlObject)
    
    Obtains the form that is currently the first form in the formbrowser
    visible to the user.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object

    Returns
    -------
        pFlForm : pointer to xfdata.FL_FORM
            first visible form

    Examples
    --------
        >>> pform = fl_get_formbrowser_topform(frmbrobj)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_get_formbrowser_topform = library.cfuncproto(
        library.load_so_libforms(), "fl_get_formbrowser_topform",
        cty.POINTER(xfdata.FL_FORM), [cty.POINTER(xfdata.FL_OBJECT)],
        """FL_FORM * fl_get_formbrowser_topform(FL_OBJECT * ob)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    library.keep_elem_refs(pFlObject)
    retval = _fl_get_formbrowser_topform(pFlObject)
    return retval


def fl_set_formbrowser_topform(pFlObject, pFlForm):
    """fl_set_formbrowser_topform(pFlObject, pFlForm)
    
    Sets which form to show by setting the top form.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        pFlForm : pointer to xfdata.FL_FORM
            form

    Returns
    -------
        seqnum : int
            sequence number of the form

    Examples
    --------
        >>> frmid = fl_set_formbrowser_topform(frmbrobj, pform)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_set_formbrowser_topform = library.cfuncproto(
        library.load_so_libforms(), "fl_set_formbrowser_topform",
        cty.c_int, [cty.POINTER(xfdata.FL_OBJECT),
        cty.POINTER(xfdata.FL_FORM)],
        """int fl_set_formbrowser_topform(FL_OBJECT * ob, FL_FORM * form)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    library.verify_flformptr_type(pFlForm)
    library.keep_elem_refs(pFlObject, pFlForm)
    retval = _fl_set_formbrowser_topform(pFlObject, pFlForm)
    return retval


def fl_set_formbrowser_topform_bynumber(pFlObject, seqnum):
    """fl_set_formbrowser_topform_bynumber(pFlObject, seqnum)
    
    Sets which form to show by setting the top form, using a sequence
    number.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        seqnum : int
            sequence number of form

    Returns
    -------
        pFlForm : pointer to xfdata.FL_FORM
            new top form

    Examples
    --------
        >>> pform = fl_set_formbrowser_topform_bynumber(frmbrobj, 2)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_set_formbrowser_topform_bynumber = library.cfuncproto(
        library.load_so_libforms(), "fl_set_formbrowser_topform_bynumber",
        cty.POINTER(xfdata.FL_FORM), [cty.POINTER(xfdata.FL_OBJECT),
        cty.c_int],
        """FL_FORM * fl_set_formbrowser_topform_bynumber( \
           FL_OBJECT * ob, int n)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    iseqnum = library.convert_to_int(seqnum)
    library.keep_elem_refs(pFlObject, seqnum, iseqnum)
    retval = _fl_set_formbrowser_topform_bynumber(pFlObject, iseqnum)
    return retval


def fl_set_formbrowser_xoffset(pFlObject, offset):
    """fl_set_formbrowser_xoffset(pFlObject, offset)
    
    Scrolls within a formbrowser in horizontal direction.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        offset : int
            positive number, measuring in pixels the offset from the natural
            position from the left. 0 indicates the natural position of the
            content within the formbrowser.

    Returns
    -------
        num. : int
            *todo*

    Examples
    --------
        >>> num = fl_set_formbrowser_xoffset(frmbrobj, 15)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_set_formbrowser_xoffset = library.cfuncproto(
        library.load_so_libforms(), "fl_set_formbrowser_xoffset",
        cty.c_int, [cty.POINTER(xfdata.FL_OBJECT), cty.c_int],
        """int fl_set_formbrowser_xoffset(FL_OBJECT * ob, int offset)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    ioffset = library.convert_to_int(offset)
    library.keep_elem_refs(pFlObject, offset, ioffset)
    retval = _fl_set_formbrowser_xoffset(pFlObject, ioffset)
    return retval


def fl_set_formbrowser_yoffset(pFlObject, offset):
    """fl_set_formbrowser_yoffset(pFlObject, offset)
    
    Scrolls within a formbrowser in vertical direction.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        offset : int
            positive number, measuring in pixels the offset from the natural
            position from the top. 0 indicates the natural position of the
            content within the formbrowser

    Returns
    -------
        num. : int
            *todo*

    Examples
    --------
        >>> num = fl_set_formbrowser_yoffset(frmbrobj, 15)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_set_formbrowser_yoffset = library.cfuncproto(
        library.load_so_libforms(), "fl_set_formbrowser_yoffset",
        cty.c_int, [cty.POINTER(xfdata.FL_OBJECT), cty.c_int],
        """int fl_set_formbrowser_yoffset(FL_OBJECT * ob, int offset)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    ioffset = library.convert_to_int(offset)
    library.keep_elem_refs(pFlObject, offset, ioffset)
    retval = _fl_set_formbrowser_yoffset(pFlObject, ioffset)
    return retval


def fl_get_formbrowser_xoffset(pFlObject):
    """fl_get_formbrowser_xoffset(pFlObject)
    
    Obtains the current horizontal offset from left in pixel of a
    formbrowser.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object

    Returns
    -------
        offset : int
            horizontal offset

    Examples
    --------
        >>> xoffset = fl_get_formbrowser_xoffset(frmbrobj)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_get_formbrowser_xoffset = library.cfuncproto(
        library.load_so_libforms(), "fl_get_formbrowser_xoffset",
        cty.c_int, [cty.POINTER(xfdata.FL_OBJECT)],
        """int fl_get_formbrowser_xoffset(FL_OBJECT * ob)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    library.keep_elem_refs(pFlObject)
    retval = _fl_get_formbrowser_xoffset(pFlObject)
    return retval


def fl_get_formbrowser_yoffset(pFlObject):
    """fl_get_formbrowser_yoffset(pFlObject)
    
    Obtains the current vertical offset from top in pixel of a
    formbrowser.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object

    Returns
    -------
        offset : int
            vertical offset

    Examples
    --------
        >>> yoffset = fl_get_formbrowser_yoffset(frmbrobj)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_get_formbrowser_yoffset = library.cfuncproto(
        library.load_so_libforms(), "fl_get_formbrowser_yoffset",
        cty.c_int, [cty.POINTER(xfdata.FL_OBJECT)],
        """int fl_get_formbrowser_yoffset(FL_OBJECT * ob)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    library.keep_elem_refs(pFlObject)
    retval = _fl_get_formbrowser_yoffset(pFlObject)
    return retval


def fl_find_formbrowser_form_number(pFlObject, pFlForm):
    """fl_find_formbrowser_form_number(pFlObject, pFlForm)
    
    Finds out the sequence number of a particular form.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        pFlForm : pointer to xfdata.FL_FORM
            form candidate to be found

    Returns
    -------
        seqnum : int
            sequence number of form

    Examples
    --------
        >>> frmid = fl_find_formbrowser_form_number(frmbrobj, pform)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_find_formbrowser_form_number = library.cfuncproto(
        library.load_so_libforms(), "fl_find_formbrowser_form_number",
        cty.c_int, [cty.POINTER(xfdata.FL_OBJECT),
        cty.POINTER(xfdata.FL_FORM)],
        """int fl_find_formbrowser_form_number(FL_OBJECT * ob,
           FL_FORM * candidate_form)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    library.verify_flformptr_type(pFlForm)
    library.keep_elem_refs(pFlObject, pFlForm)
    retval = _fl_find_formbrowser_form_number(pFlObject, pFlForm)
    return retval


def fl_add_formbrowser(frmbrwstype, x, y, w, h, label):
    """fl_add_formbrowser(frmbrwstype, x, y, w, h, label)
    
    Adds a formbrowser object.

    Parameters
    ----------
        frmbrwstype : int
            type of formbrowser to be added. Values (from xfdata.py)
            FL_NORMAL_FORMBROWSER
        x : int
            horizontal position (upper-left corner)
        y : int
            vertical position (upper-left corner)
        w : int
            width in coord units
        h : int
            height in coord units
        label : str
            text label of formbrowser

    Returns
    -------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object added

    Examples
    --------
        >>> frmbrobj = fl_add_formbrowser(xfdata.FL_NORMAL_FORMBROWSER,
                110, 60, 550, 750, "My Formbrowser)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_add_formbrowser = library.cfuncproto(
        library.load_so_libforms(), "fl_add_formbrowser",
        cty.POINTER(xfdata.FL_OBJECT), [cty.c_int, xfdata.FL_Coord,
        xfdata.FL_Coord, xfdata.FL_Coord, xfdata.FL_Coord, xfdata.STRING],
        """FL_OBJECT * fl_add_formbrowser(int type, FL_Coord x,
           FL_Coord y, FL_Coord w, FL_Coord h, const char * label)""")
    library.check_if_initialized()
    library.checkfatal_allowed_value_in_list(frmbrwstype, \
            xfdata.FORMBRWSTYPE_list)
    ifrmbrwstype = library.convert_to_int(frmbrwstype)
    ix = library.convert_to_FL_Coord(x)
    iy = library.convert_to_FL_Coord(y)
    iw = library.convert_to_FL_Coord(w)
    ih = library.convert_to_FL_Coord(h)
    slabel = library.convert_to_string(label)
    library.keep_elem_refs(frmbrwstype, x, y, w, h, label, ifrmbrwstype, \
            ix, iy, iw, ih, slabel)
    retval = _fl_add_formbrowser(ifrmbrwstype, ix, iy, iw, ih, slabel)
    return retval


# fl_create_formbrowser function placeholder (internal)


def fl_get_formbrowser_numforms(pFlObject):
    """fl_get_formbrowser_numforms(pFlObject)
    
    Obtains the total number of forms in a formbrowser object.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object

    Returns
    -------
        numforms : int
            number of forms in formbrowser

    Examples
    --------
        >>> frmsnum = fl_get_formbrowser_numforms(frmbrobj)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_get_formbrowser_numforms = library.cfuncproto(
        library.load_so_libforms(), "fl_get_formbrowser_numforms",
        cty.c_int, [cty.POINTER(xfdata.FL_OBJECT)],
        """int fl_get_formbrowser_numforms(FL_OBJECT * ob)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    library.keep_elem_refs(pFlObject)
    retval = _fl_get_formbrowser_numforms(pFlObject)
    return retval


def fl_get_formbrowser_form(pFlObject, seqnum):
    """fl_get_formbrowser_form(pFlObject, seqnum)
    
    Obtains the form handle from the sequence number.

    Parameters
    ----------
        pFlObject : pointer to xfdata.FL_OBJECT
            formbrowser object
        seqnum : int
            sequence number of the form

    Returns
    -------
        pFlForm : pointer to xfdata.FL_FORM
            form

    Examples
    --------
        >>> pform = fl_get_formbrowser_form(frmbrobj, 2)

    Notes
    -----
        Status: Tested + Doc + NoDemo = OK

    """
    _fl_get_formbrowser_form = library.cfuncproto(
        library.load_so_libforms(), "fl_get_formbrowser_form",
        cty.POINTER(xfdata.FL_FORM), [cty.POINTER(xfdata.FL_OBJECT),
        cty.c_int],
        """FL_FORM * fl_get_formbrowser_form(FL_OBJECT * ob, int n)""")
    library.check_if_initialized()
    library.verify_flobjectptr_type(pFlObject)
    iseqnum = library.convert_to_int(seqnum)
    library.keep_elem_refs(pFlObject, seqnum, iseqnum)
    retval = _fl_get_formbrowser_form(pFlObject, iseqnum)
    return retval

