#!/usr/bin/env python
# -*- coding: iso8859-1 -*-

"""
    xforms-python
    Python wrapper for XForms (X11) GUI C toolkit library using ctypes

    Copyright (C) 2009  Luca Lazzaroni "LukenShiro"  <lukenshiro@ngi.it>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as
    published by the Free Software Foundation, version 2.1 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU LGPL along with this
    program. If not, see <http://www.gnu.org/licenses/>.

    See CREDITS file to read XForms, ctypes and other acknowledgements
    and thanks.
"""

# originally generated by 'h2xml+gccxml' and 'xml2py'
# then heavily reordered and reworked

####################################################
# Constants used by XForms shared object libraries #
####################################################


FL_VERSION = 1
FL_REVISION = 0
FL_FIXLEVEL = "92sp2"
FL_INCLUDE_VERSION = (FL_VERSION * 1000 + FL_REVISION)


########################################
# forms.h (Basic.h)
#  Basic definitions and limits.
#  Window system independent prototypes
#  Modify with care
########################################

# Some general constants
FL_ON = 1
FL_OK = 1
FL_VALID = 1
FL_PREEMPT = 1
FL_AUTO = 2
FL_WHEN_NEEDED = FL_AUTO        #2
FL_OFF = 0
FL_CANCEL = 0
FL_INVALID = 0
FL_NONE = 0     # defined elsewhere
# WM_DELETE_WINDOW callback return
FL_IGNORE = -1
FL_CLOSE = -2
# miscty. return types
FL_ARGUMENT = -3
FL_ALLOC = -4
FL_BAD_OBJECT = -5

# max directory length
# FL_PATH_MAX / PATH_MAX
FL_PATH_MAX = 1024

# The screen coordinate unit, FL_Coord, must be of signed type.
# If FL_Coord is float, FL_CoordIsFloat must be defined to be 1 so that
# round-off error can be checked. **TODO Float not tested
Fl_CoordIsFloat = 0     # make it 1 if FL_Coord is of type float of type float


# Coordinates can be in pixels, milli-meters or points (1/72inch)
# values for enumeration 'FL_COORD_UNIT'
FL_COORD_PIXEL = 0          # default, Pixel
FL_COORD_MM = 1             # milli-meter
FL_COORD_POINT = 2          # point
FL_COORD_centiMM = 3        # one hundredth of a mm
FL_COORD_centiPOINT = 4     # one hundredth of a point

# All object classes.
# values for enumeration 'FL_CLASS'
FL_INVALID_CLASS = 0
FL_BUTTON = 1
FL_LIGHTBUTTON = 2
FL_ROUNDBUTTON = 3
FL_ROUND3DBUTTON = 4
FL_CHECKBUTTON = 5
FL_BITMAPBUTTON = 6
FL_PIXMAPBUTTON = 7
FL_BITMAP = 8
FL_PIXMAP = 9
FL_BOX = 10
FL_TEXT = 11
FL_MENU = 12
FL_CHART = 13
FL_CHOICE = 14
FL_COUNTER = 15
FL_SLIDER = 16
FL_VALSLIDER = 17
FL_INPUT = 18
FL_BROWSER = 19
FL_DIAL = 20
FL_TIMER = 21
FL_CLOCK = 22
FL_POSITIONER = 23
FL_FREE = 24
FL_XYPLOT = 25
FL_FRAME = 26
FL_LABELFRAME = 27
FL_CANVAS = 28
FL_GLCANVAS = 29
FL_TABFOLDER = 30
FL_SCROLLBAR = 31
FL_SCROLLBUTTON = 32
FL_MENUBAR = 33
FL_TEXTBOX = 34             # internal use
FL_LABELBUTTON = 35
FL_COMBOBOX = 36
FL_IMAGECANVAS = 37
FL_THUMBWHEEL = 38
FL_COLORWHEEL = 39
FL_FORMBROWSER = 40
FL_SELECT = 41
FL_NMENU = 42
FL_SPINNER = 43
FL_TBOX = 44
FL_CLASS_END = 45           # sentinel

FL_BEGIN_GROUP = 10000
FL_END_GROUP = 20000

FL_USER_CLASS_START = 1001      # min. user class value
FL_USER_CLASS_END = 9999        # max. user class value

# maximum border width (in pixel)
FL_MAX_BW = 10

# how to display a form onto screen
# values for enumeration 'FL_PLACE'
FL_PLACE_FREE = 0             # size remain resizable
FL_PLACE_MOUSE = 1            # mouse centered on form
FL_PLACE_CENTER = 2           # center of the screen
FL_PLACE_POSITION = 4         # specific size
FL_PLACE_SIZE = 8             # specific size
FL_PLACE_GEOMETRY = 16        # specific position
FL_PLACE_ASPECT =  32         # keep aspect ratio
FL_PLACE_FULLSCREEN = 64      # scale to fit screen
FL_PLACE_HOTSPOT = 128        # so mouse fall on (x,y)
FL_PLACE_ICONIC = 256
# modifiers
FL_FREE_SIZE = 16384          #(1<<14)
FL_FIX_SIZE = 32768           #(1<<15)

FL_PLACE_FREE_CENTER = (FL_PLACE_CENTER|FL_FREE_SIZE)
FL_PLACE_CENTERFREE = (FL_PLACE_CENTER|FL_FREE_SIZE)

# Window manager decoration request and forms attributes
# values for unnamed enumeration
FL_FULLBORDER = 1       # normal
FL_TRANSIENT = 2        # set TRANSIENT_FOR property
FL_NOBORDER = 3         # use override_redirect to supress decor.
FL_MODAL = 256          #1<<8  not implemented yet

# All box types
# values for enumeration 'FL_BOX_TYPE'
FL_NO_BOX = 0
FL_UP_BOX = 1
FL_DOWN_BOX = 2
FL_BORDER_BOX = 3
FL_SHADOW_BOX = 4
FL_FRAME_BOX = 5
FL_ROUNDED_BOX = 6
FL_EMBOSSED_BOX = 7
FL_FLAT_BOX = 8
FL_RFLAT_BOX = 9
FL_RSHADOW_BOX = 10
FL_OVAL_BOX = 11
FL_ROUNDED3D_UPBOX = 12
FL_ROUNDED3D_DOWNBOX = 13
FL_OVAL3D_UPBOX = 14
FL_OVAL3D_DOWNBOX = 15
FL_OVAL3D_FRAMEBOX = 16
FL_OVAL3D_EMBOSSEDBOX = 17
# for internal use only
FL_TOPTAB_UPBOX = 18
FL_SELECTED_TOPTAB_UPBOX = 19
FL_BOTTOMTAB_UPBOX = 20
FL_SELECTED_BOTTOMTAB_UPBOX = 21
FL_OSHADOW_BOX = 22                   # not used
FL_MAX_BOX_STYLES = 23                # sentinel


# How to place text relative to a box
# values for enumeration 'FL_ALIGN'
FL_ALIGN_CENTER = 0
FL_ALIGN_TOP = 1
FL_ALIGN_BOTTOM = 2
FL_ALIGN_LEFT = 4
FL_ALIGN_RIGHT = 8
FL_ALIGN_LEFT_TOP = (FL_ALIGN_TOP|FL_ALIGN_LEFT)
FL_ALIGN_RIGHT_TOP = (FL_ALIGN_TOP|FL_ALIGN_RIGHT)
FL_ALIGN_LEFT_BOTTOM = (FL_ALIGN_BOTTOM|FL_ALIGN_LEFT)
FL_ALIGN_RIGHT_BOTTOM = (FL_ALIGN_BOTTOM|FL_ALIGN_RIGHT)
FL_ALIGN_INSIDE = 8192      # (1<<13)
FL_ALIGN_VERT = 16384       # (1<<14)  not functional yet
# the rest is for backward compatibility only, don't use!
FL_ALIGN_TOP_LEFT     = FL_ALIGN_LEFT_TOP
FL_ALIGN_TOP_RIGHT    = FL_ALIGN_RIGHT_TOP
FL_ALIGN_BOTTOM_LEFT  = FL_ALIGN_LEFT_BOTTOM
FL_ALIGN_BOTTOM_RIGHT = FL_ALIGN_RIGHT_BOTTOM

# Mouse buttons. Don't have to be consecutive
# values for unnamed enumeration
FL_MBUTTON1 = 1
FL_MBUTTON2 = 2
FL_MBUTTON3 = 3
FL_MBUTTON4 = 4
FL_MBUTTON5 = 5

FL_LEFT_MOUSE = FL_MBUTTON1
FL_MIDDLE_MOUSE = FL_MBUTTON2
FL_RIGHT_MOUSE = FL_MBUTTON3
FL_SCROLLUP_MOUSE = FL_MBUTTON4
FL_SCROLLDOWN_MOUSE = FL_MBUTTON5

FL_LEFTMOUSE = FL_LEFT_MOUSE
FL_MIDDLEMOUSE = FL_MIDDLE_MOUSE
FL_RIGHTMOUSE = FL_RIGHT_MOUSE
FL_SCROLLUPMOUSE = FL_SCROLLUP_MOUSE
FL_SCROLLDOWNMOUSE = FL_SCROLLDOWN_MOUSE

# control when to return input, slider and dial etc. object.
# values for unnamed enumeration
FL_RETURN_NONE = 0
FL_RETURN_CHANGED = 1
FL_RETURN_END = 2
FL_RETURN_END_CHANGED = 4
FL_RETURN_SELECTION = 8
FL_RETURN_DESELECTION = 16
FL_RETURN_TRIGGERED = 1024
FL_RETURN_ALWAYS = ~ FL_RETURN_END_CHANGED

# Some special color indices for FL private colormap.
# It does not matter  what the value of each enum is,
# but it must start from 0 and be consecutive.
# values for enumeration 'FL_PD_COL'
FL_BLACK = 0
FL_RED = 1
FL_GREEN = 2
FL_YELLOW = 3
FL_BLUE = 4
FL_MAGENTA = 5
FL_CYAN = 6
FL_WHITE = 7
FL_TOMATO = 8
FL_INDIANRED = 9
FL_SLATEBLUE = 10
FL_COL1 = 11
FL_RIGHT_BCOL = 12
FL_BOTTOM_BCOL = 13
FL_TOP_BCOL = 14
FL_LEFT_BCOL = 15
FL_MCOL = 16
FL_INACTIVE = 17
FL_PALEGREEN = 18
FL_DARKGOLD = 19
FL_ORCHID = 20
FL_DARKCYAN = 21
FL_DARKTOMATO = 22
FL_WHEAT = 23
FL_DARKORANGE = 24
FL_DEEPPINK = 25
FL_CHARTREUSE = 26
FL_DARKVIOLET = 27
FL_SPRINGGREEN = 28
FL_DODGERBLUE = 29
FL_LIGHTER_COL1 = 30
FL_DARKER_COL1 = 31
FL_ALICEBLUE = 32
FL_ANTIQUEWHITE = 33
FL_AQUA = 34
FL_AQUAMARINE = 35
FL_AZURE = 36
FL_BEIGE = 37
FL_BISQUE = 38
FL_BLANCHEDALMOND = 39
FL_BLUEVIOLET = 40
FL_BROWN = 41
FL_BURLYWOOD = 42
FL_CADETBLUE = 43
FL_CHOCOLATE = 44
FL_CORAL = 45
FL_CORNFLOWERBLUE = 46
FL_CORNSILK = 47
FL_CRIMSON = 48
FL_DARKBLUE = 49
FL_DARKGOLDENROD = 50
FL_DARKGRAY = 51
FL_DARKGREEN = 52
FL_DARKGREY = 53
FL_DARKKHAKI = 54
FL_DARKMAGENTA = 55
FL_DARKOLIVEGREEN = 56
FL_DARKORCHID = 57
FL_DARKRED = 58
FL_DARKSALMON = 59
FL_DARKSEAGREEN = 60
FL_DARKSLATEBLUE = 61
FL_DARKSLATEGRAY = 62
FL_DARKSLATEGREY = 63
FL_DARKTURQUOISE = 64
FL_DEEPSKYBLUE = 65
FL_DIMGRAY = 66
FL_DIMGREY = 67
FL_FIREBRICK = 68
FL_FLORALWHITE = 69
FL_FORESTGREEN = 70
FL_FUCHSIA = 71
FL_GAINSBORO = 72
FL_GHOSTWHITE = 73
FL_GOLD = 74
FL_GOLDENROD = 75
FL_GRAY = 76
FL_GREENYELLOW = 77
FL_GREY = 78
FL_HONEYDEW = 79
FL_HOTPINK = 80
FL_INDIGO = 81
FL_IVORY = 82
FL_KHAKI = 83
FL_LAVENDER = 84
FL_LAVENDERBLUSH = 85
FL_LAWNGREEN = 86
FL_LEMONCHIFFON = 87
FL_LIGHTBLUE = 88
FL_LIGHTCORAL = 89
FL_LIGHTCYAN = 90
FL_LIGHTGOLDENRODYELLOW = 91
FL_LIGHTGRAY = 92
FL_LIGHTGREEN = 93
FL_LIGHTGREY = 94
FL_LIGHTPINK = 95
FL_LIGHTSALMON = 96
FL_LIGHTSEAGREEN = 97
FL_LIGHTSKYBLUE = 98
FL_LIGHTSLATEGRAY = 99
FL_LIGHTSLATEGREY = 100
FL_LIGHTSTEELBLUE = 101
FL_LIGHTYELLOW = 102
FL_LIME = 103
FL_LIMEGREEN = 104
FL_LINEN = 105
FL_MAROON = 106
FL_MEDIUMAQUAMARINE = 107
FL_MEDIUMBLUE = 108
FL_MEDIUMORCHID = 109
FL_MEDIUMPURPLE = 110
FL_MEDIUMSEAGREEN = 111
FL_MEDIUMSLATEBLUE = 112
FL_MEDIUMSPRINGGREEN = 113
FL_MEDIUMTURQUOISE = 114
FL_MEDIUMVIOLETRED = 115
FL_MIDNIGHTBLUE = 116
FL_MINTCREAM = 117
FL_MISTYROSE = 118
FL_MOCCASIN = 119
FL_NAVAJOWHITE = 120
FL_NAVY = 121
FL_OLDLACE = 122
FL_OLIVE = 123
FL_OLIVEDRAB = 124
FL_ORANGE = 125
FL_ORANGERED = 126
FL_PALEGOLDENROD = 127
FL_PALETURQUOISE = 128
FL_PALEVIOLETRED = 129
FL_PAPAYAWHIP = 130
FL_PEACHPUFF = 131
FL_PERU = 132
FL_PINK = 133
FL_PLUM = 134
FL_POWDERBLUE = 135
FL_PURPLE = 136
FL_ROSYBROWN = 137
FL_ROYALBLUE = 138
FL_SADDLEBROWN = 139
FL_SALMON = 140
FL_SANDYBROWN = 141
FL_SEAGREEN = 142
FL_SEASHELL = 143
FL_SIENNA = 144
FL_SILVER = 145
FL_SKYBLUE = 146
FL_SLATEGRAY = 147
FL_SLATEGREY = 148
FL_SNOW = 149
FL_STEELBLUE = 150
FL_TAN = 151
FL_TEAL = 152
FL_THISTLE = 153
FL_TURQUOISE = 154
FL_VIOLET = 155
FL_WHITESMOKE = 156
FL_YELLOWGREEN = 157
FL_FREE_COL1 = 256
FL_FREE_COL2 = 257
FL_FREE_COL3 = 258
FL_FREE_COL4 = 259
FL_FREE_COL5 = 260
FL_FREE_COL6 = 261
FL_FREE_COL7 = 262
FL_FREE_COL8 = 263
FL_FREE_COL9 = 264
FL_FREE_COL10 = 265
FL_FREE_COL11 = 266
FL_FREE_COL12 = 267
FL_FREE_COL13 = 268
FL_FREE_COL14 = 269
FL_FREE_COL15 = 270
FL_FREE_COL16 = 271
FL_NOCOLOR = 2147483647           #INT_MAX

FL_BUILT_IN_COLS = FL_YELLOWGREEN + 1
FL_INACTIVE_COL = FL_INACTIVE

# Some aliases for the color. This is actually backwards ...
FL_GRAY16 = FL_RIGHT_BCOL
FL_GRAY35 = FL_BOTTOM_BCOL
FL_GRAY80 = FL_TOP_BCOL
FL_GRAY90 = FL_LEFT_BCOL
FL_GRAY63 = FL_COL1
FL_GRAY75 = FL_MCOL
FL_LCOL = FL_BLACK
FL_NoColor = FL_NOCOLOR

# An alias probably for an earlier typo
FL_DOGERBLUE = FL_DODGERBLUE

# Events that a form reacts to.
# values for enumeration 'FL_EVENTS'
FL_NOEVENT = 0
FL_DRAW = 1
FL_PUSH = 2
FL_RELEASE = 3
FL_ENTER = 4
FL_LEAVE = 5
FL_MOTION = 6
FL_FOCUS = 7
FL_UNFOCUS = 8
FL_KEYBOARD = 9
FL_KEYPRESS = FL_KEYBOARD
FL_UPDATE = 10      # for objects that need to update something from time to
                    # time
FL_MOUSE = FL_UPDATE
FL_STEP = 11
FL_SHORTCUT = 12
FL_FREEMEM = 13
FL_OTHER = 14       # property, selection etc
FL_DRAWLABEL = 15
FL_DBLCLICK = 16    # double click
FL_TRPLCLICK = 17   # triple click
FL_ATTRIB = 18      # attribute change
FL_KEYRELEASE = 19
FL_PS = 20          # dump a form into EPS
FL_MOVEORIGIN = 21  # dragging the form across the screen changes its
                    # absolute x,y coords. Objects that themselves
                    # contain forms should ensure that they are up to
                    # date.
FL_RESIZED = 22     # the object has been resized by scale_form
                    # Tell it that this has happened so that
                    # it can resize any FL_FORMs that it contains.

FL_MOVE = FL_MOTION    # for compatibility

# Resize policies
# values for enumeration 'FL_RESIZE_T'
FL_RESIZE_NONE = 0
FL_RESIZE_X = 1
FL_RESIZE_Y = 2
FL_RESIZE_ALL = (FL_RESIZE_X|FL_RESIZE_Y)

# Keyboard focus control
# values for enumeration 'FL_KEY'
FL_KEY_NORMAL  = 1     # normal keys(0-255) - tab +left/right
FL_KEY_TAB     = 2     # normal keys + 4 direction cursor
FL_KEY_SPECIAL = 4     # only needs special keys(>255)
FL_KEY_ALL     = 7     # all keys

FL_ALT_MASK = (1L<<25)      # alt + Key --> FL_ALT_MASK + key
FL_CONTROL_MASK = (1L<<26)
FL_SHIFT_MASK = (1L<<27)
FL_ALT_VAL = FL_ALT_MASK    # Don't use!

MAX_SHORTCUTS = 8

# Pop-up menu item attributes. NOTE if more than 8, need to change
# choice and menu class where mode is kept by a single byte
# values for unnamed enumeration
FL_PUP_NONE = 0
FL_PUP_GREY = 1
FL_PUP_BOX = 2
FL_PUP_CHECK = 4
FL_PUP_RADIO = 8

FL_PUP_GRAY = FL_PUP_GREY
FL_PUP_TOGGLE = FL_PUP_BOX          # not used anymore
FL_PUP_INACTIVE = FL_PUP_GREY


# ***** FONTS *****

FL_MAXFONTS = 48        # max number of fonts

# values for enumeration 'FL_TEXT_STYLE'
FL_INVALID_STYLE = -1
FL_NORMAL_STYLE = 0
FL_BOLD_STYLE = 1
FL_ITALIC_STYLE = 2
FL_BOLDITALIC_STYLE = 3
FL_FIXED_STYLE = 4
FL_FIXEDBOLD_STYLE = 5
FL_FIXEDITALIC_STYLE = 6
FL_FIXEDBOLDITALIC_STYLE = 7
FL_TIMES_STYLE = 8
FL_TIMESBOLD_STYLE = 9
FL_TIMESITALIC_STYLE = 10
FL_TIMESBOLDITALIC_STYLE = 11
FL_MISC_STYLE = 12
FL_MISCBOLD_STYLE = 13
FL_MISCITALIC_STYLE = 14
FL_SYMBOL_STYLE = 15
# modifier masks. Need to fit a short
FL_SHADOW_STYLE = 512           #(1<<9)
FL_ENGRAVED_STYLE = 1024        #(1<<10)
FL_EMBOSSED_STYLE = 2048        #(1<<11)


# Standard sizes in XForms
FL_TINY_SIZE = 8
FL_SMALL_SIZE = 10
FL_NORMAL_SIZE = 12
FL_MEDIUM_SIZE = 14
FL_LARGE_SIZE = 18
FL_HUGE_SIZE = 24
FL_DEFAULT_SIZE = FL_SMALL_SIZE

# Defines for compatibility
FL_TINY_FONT = FL_TINY_SIZE
FL_SMALL_FONT = FL_SMALL_SIZE
FL_NORMAL_FONT = FL_NORMAL_SIZE
FL_MEDIUM_FONT = FL_MEDIUM_SIZE
FL_LARGE_FONT = FL_LARGE_SIZE
FL_HUGE_FONT = FL_HUGE_SIZE
FL_NORMAL_FONT1 = FL_SMALL_FONT
FL_NORMAL_FONT2 = FL_NORMAL_FONT
FL_DEFAULT_FONT = FL_SMALL_FONT

#FL_BOUND_WIDTH = FL_Coord(1)     # Border width of boxes
FL_BOUND_WIDTH = 1     # Border width of boxes

# Definition of basic struct that holds an object

FL_CLICK_TIMEOUT = 400      # double click interval


# form visibility state: form->visible
# values for unnamed enumeration
FL_BEING_HIDDEN = -1
FL_HIDDEN = 0
FL_INVISIBLE = FL_HIDDEN
FL_VISIBLE = 1


# Async IO stuff
FL_READ   = 1
FL_WRITE  = 2
FL_EXCEPT = 4


FL_MAX_MENU_CHOICE_ITEMS = 128


# Draw mode
# values for unnamed enumeration
FL_XOR = 6              # GXxor
FL_COPY = 3             # GXcopy
FL_AND = 1              # GXand

FL_MINDEPTH = 1

# FL_xxx does not do anything anymore, but kept for compatibility
# values for unnamed enumeration
FL_IllegalVisual = -1
FL_StaticGray = 0           # StaticGray
FL_GrayScale = 1            # GrayScale
FL_StaticColor = 2          # StaticColor
FL_PseudoColor = 3          # PseudoColor
FL_TrueColor = 4            # TrueColor
FL_DirectColor = 5          # DirectColor
FL_DefaultVisual = 10       # special request

# my add --LK
TrueColor = FL_TrueColor
DirectColor = FL_DirectColor

# values for unnamed enumeration
FL_North = 2                            #NorthGravity
FL_NorthEast = 3                        #NorthEastGravity
FL_NorthWest = 1                        #NorthWestGravity
FL_South = 8                            #SouthGravity
FL_SouthEast = 9                        #SouthEastGravity
FL_SouthWest = 7                        #SouthWestGravity
FL_East = 6                             #EastGravity
FL_West = 4                             #WestGravity
FL_NoGravity = 0                        #ForgetGravity
FL_ForgetGravity = FL_NoGravity         #ForgetGravity

GreyScale = GrayScale = 1           #GrayScale
StaticGrey = StaticGray = 0         #StaticGray


# Internal colormap size. Not really very meaningful as fl_mapcolor
# and company allow color "leakage", that is, although only FL_MAX_COLS
# are kept in the internal colormap, the server might have substantially
# more colors allocated
FL_MAX_COLORS = 1024
FL_MAX_COLS = FL_MAX_COLORS


# Fonts related

# Already defined in xfstruct.py
#FL_MAX_FONTSIZES = 10


# Line attributes

# values for unnamed enumeration
FL_SOLID = 0                 #LineSolid
FL_USERDASH = 1               #LineOnOffDash
FL_USERDOUBLEDASH = 2        #LineDoubleDash
FL_DOT = 3
FL_DOTDASH = 4
FL_DASH = 5
FL_LONGDASH = 6



# *** start - from /usr/include/X11/X.h ***
# Input Event Masks. Used as event-mask window attribute and as arguments
# to Grab requests.  Not to be confused with event names.
NoEventMask = 0L
KeyPressMask = (1L<<0)
KeyReleaseMask = (1L<<1)
ButtonPressMask = (1L<<2)
ButtonReleaseMask = (1L<<3)
EnterWindowMask = (1L<<4)
LeaveWindowMask = (1L<<5)
PointerMotionMask = (1L<<6)
PointerMotionHintMask = (1L<<7)
Button1MotionMask = (1L<<8)
Button2MotionMask = (1L<<9)
Button3MotionMask = (1L<<10)
Button4MotionMask = (1L<<11)
Button5MotionMask = (1L<<12)
ButtonMotionMask = (1L<<13)
KeymapStateMask = (1L<<14)
ExposureMask = (1L<<15)
VisibilityChangeMask = (1L<<16)
StructureNotifyMask = (1L<<17)
ResizeRedirectMask = (1L<<18)
SubstructureNotifyMask = (1L<<19)
SubstructureRedirectMask = (1L<<20)
FocusChangeMask = (1L<<21)
ColormapChangeMask = (1L<<23)
OwnerGrabButtonMask = (1L<<24)
# Key masks. Used as modifiers to GrabButton and GrabKey, results of QueryPointer,
# state in various key-, mouse-, and button-related events.
ShiftMask = (1<<0)
LockMask = (1<<1)
ControlMask = (1<<2)
Mod1Mask = (1<<3)
Mod2Mask = (1<<4)
Mod3Mask = (1<<5)
Mod4Mask = (1<<6)
Mod5Mask = (1<<7)
# button masks.  Used in same manner as Key masks above. Not to be confused
# with button names below.
Button1Mask = (1<<8)
Button2Mask = (1<<9)
Button3Mask = (1<<10)
Button4Mask = (1<<11)
Button5Mask = (1<<12)
AnyModifier = (1<<15)       # used in GrabButton, GrabKey
# *** end - from /usr/include/X11/X.h ***

# All registerable events, including Client Message
FL_ALL_EVENT = (KeyPressMask | KeyReleaseMask \
                    | ButtonPressMask | ButtonReleaseMask \
                    | EnterWindowMask | LeaveWindowMask \
                    | ButtonMotionMask | PointerMotionMask )


# Resources

# values for enumeration 'FL_RTYPE'
FL_NONE = 0
FL_SHORT = 10
FL_BOOL = 11
FL_INT = 12
FL_LONG = 13
FL_FLOAT = 14
FL_STRING = 15


# values for enumeration 'XrmOptionKind'
XrmoptionNoArg = 0      # Value is specified in OptionDescRec.value
XrmoptionIsArg = 1      # Value is the option string itself
XrmoptionStickyArg = 2  # Value is characters immediately following option
XrmoptionSepArg = 3     # Value is next argument in argv
XrmoptionResArg = 4     # Resource and value in next argument in argv
XrmoptionSkipArg = 5    # Ignore this option and the next argument in argv
XrmoptionSkipLine = 6   # Ignore this option and the rest of argv
XrmoptionSkipNArgs = 7  # Ignore this option and the next
                        # OptionDescRes.value arguments in argv


# Program default masks

# values for unnamed enumeration
FL_PDDepth = 2                      #(1<<1)
FL_PDClass = 4                      #(1<<2)
FL_PDDouble = 8                     #(1<<3)
FL_PDSync = 16                      #(1<<4)
FL_PDPrivateMap = 32                #(1<<5)
FL_PDScrollbarType = 64             #(1<<6)
FL_PDPupFontSize = 128              #(1<<7)
FL_PDButtonFontSize = 256           #(1<<8)
FL_PDInputFontSize = 512            #(1<<9)
FL_PDSliderFontSize  = 1024         #(1<<10)
FL_PDVisual = 2048                  #(1<<11)
FL_PDULThickness = 4096             #(1<<12)
FL_PDULPropWidth = 8192             #(1<<13)
FL_PDBS = 16384                     #(1<<14)
FL_PDCoordUnit = 32768              #(1<<15)
FL_PDDebug = 65536                  #(1<<16)
FL_PDSharedMap = 131072             #(1<<17)
FL_PDStandardMap = 262144           #(1<<18)
FL_PDBorderWidth = 524288           #(1<<19)
FL_PDSafe = 1048576                 #(1<<20)
FL_PDMenuFontSize = 2097152         #(1<<21)
FL_PDBrowserFontSize = 4194304      #(1<<22)
FL_PDChoiceFontSize = 8388608       #(1<<23)
FL_PDLabelFontSize = 16777216       #(1<<24)

FL_PDButtonLabelSize = FL_PDButtonFontSize
FL_PDSliderLabelSize = FL_PDSliderFontSize
FL_PDInputLabelSize = FL_PDInputFontSize
FL_PDButtonLabel = FL_PDButtonLabelSize


# How we pack and unpack colors

FL_PCBITS = 8
FL_PCMAX = (1<<FL_PCBITS) - 1


FL_RMASK = 0x000000ff
FL_RSHIFT = 0
FL_GMASK = 0x0000ff00
FL_GSHIFT = 8
FL_BMASK = 0x00ff0000
FL_BSHIFT = 16
FL_AMASK = 0xff000000
FL_ASHIFT = 24


# Popup policies
# values for unnamed enumeration
FL_POPUP_NORMAL_SELECT = 0
FL_POPUP_DRAG_SELECT = 1

# Popup states
# values for unnamed enumeration
FL_POPUP_NONE = 0
FL_POPUP_DISABLED = 1       # entry is disabled
FL_POPUP_HIDDEN   = 2       # entry is temporarily hidden
FL_POPUP_CHECKED  = 4       # toggle/radio item is in on state

# Popup entry types
# values for unnamed enumeration
FL_POPUP_NORMAL = 0         # normal popup entry
FL_POPUP_TOGGLE = 1         # toggle ("binary") popup entry
FL_POPUP_RADIO = 2          # radio popup entry
FL_POPUP_SUB = 3            # sub-popup popup entry
FL_POPUP_LINE = 4           # line popup entry

# Popup color types
# values for unnamed enumeration
FL_POPUP_BACKGROUND_COLOR = 0
FL_POPUP_HIGHLIGHT_COLOR = 1
FL_POPUP_TITLE_COLOR = 2
FL_POPUP_TEXT_COLOR = 3
FL_POPUP_HIGHLIGHT_TEXT_COLOR = 4
FL_POPUP_DISABLED_TEXT_COLOR = 5
FL_POPUP_RADIO_COLOR = 6


#######################
# forms.h (bitmap.h)
# Object Class: Bitmap
#######################

FL_NORMAL_BITMAP = 0

# Defaults
FL_BITMAP_BOXTYPE = FL_NO_BOX
FL_BITMAP_COL1 = FL_COL1            # background of bitmap
FL_BITMAP_COL2 = FL_COL1            # not used currently
FL_BITMAP_LCOL = FL_LCOL            # foreground of bitmap
FL_BITMAP_ALIGN = FL_ALIGN_BOTTOM


# PIXMAP stuff

FL_NORMAL_PIXMAP = 0


#######################
# forms.h (browser.h)
# Object class Browser
#######################

# values for enumeration 'FL_BROWSER_TYPE'
FL_NORMAL_BROWSER = 0
FL_SELECT_BROWSER = 1
FL_HOLD_BROWSER = 2
FL_MULTI_BROWSER = 3

# Defaults
FL_BROWSER_BOXTYPE = FL_DOWN_BOX
FL_BROWSER_COL1 = FL_COL1
FL_BROWSER_COL2 = FL_YELLOW
FL_BROWSER_LCOL = FL_LCOL
FL_BROWSER_ALIGN = FL_ALIGN_BOTTOM

# Others
FL_BROWSER_SLCOL = FL_COL1
FL_BROWSER_FONTSIZE = FL_SMALL_FONT

# This exists only for backward compatibility and isn't used anymore!
FL_BROWSER_LINELENGTH = 2048


#############################################################
# forms.h (button.h)
# All Buttons: regular button, light button and round button
#############################################################

# values for enumeration 'FL_BUTTON_TYPE'
FL_NORMAL_BUTTON = 0
FL_PUSH_BUTTON = 1
FL_RADIO_BUTTON = 2
FL_HIDDEN_BUTTON = 3
FL_TOUCH_BUTTON = 4
FL_INOUT_BUTTON = 5
FL_RETURN_BUTTON = 6
FL_HIDDEN_RET_BUTTON = 7
FL_MENU_BUTTON = 8

FL_TOGGLE_BUTTON = FL_PUSH_BUTTON

# normal button default
FL_BUTTON_BOXTYPE = FL_UP_BOX
FL_BUTTON_COL1 = FL_COL1
FL_BUTTON_COL2 = FL_COL1
FL_BUTTON_LCOL = FL_LCOL
FL_BUTTON_ALIGN = FL_ALIGN_CENTER
FL_BUTTON_MCOL1 = FL_MCOL
FL_BUTTON_MCOL2 = FL_MCOL
FL_BUTTON_BW = FL_BOUND_WIDTH

# light button defaults
FL_LIGHTBUTTON_BOXTYPE = FL_UP_BOX
FL_LIGHTBUTTON_COL1 = FL_COL1
FL_LIGHTBUTTON_COL2 = FL_YELLOW
FL_LIGHTBUTTON_LCOL = FL_LCOL
FL_LIGHTBUTTON_ALIGN = FL_ALIGN_CENTER
FL_LIGHTBUTTON_TOPCOL = FL_COL1
FL_LIGHTBUTTON_MCOL = FL_MCOL
FL_LIGHTBUTTON_MINSIZE = 12

# round button defaults
FL_ROUNDBUTTON_BOXTYPE = FL_NO_BOX
FL_ROUNDBUTTON_COL1 = FL_MCOL
FL_ROUNDBUTTON_COL2 = FL_YELLOW
FL_ROUNDBUTTON_LCOL = FL_LCOL
FL_ROUNDBUTTON_ALIGN = FL_ALIGN_CENTER
FL_ROUNDBUTTON_TOPCOL = FL_COL1
FL_ROUNDBUTTON_MCOL = FL_MCOL

# round3d button defaults
FL_ROUND3DBUTTON_BOXTYPE = FL_NO_BOX
FL_ROUND3DBUTTON_COL1 = FL_COL1
FL_ROUND3DBUTTON_COL2 = FL_BLACK
FL_ROUND3DBUTTON_LCOL = FL_LCOL
FL_ROUND3DBUTTON_ALIGN = FL_ALIGN_CENTER
FL_ROUND3DBUTTON_TOPCOL = FL_COL1
FL_ROUND3DBUTTON_MCOL = FL_MCOL

# check button defaults
FL_CHECKBUTTON_BOXTYPE = FL_NO_BOX
FL_CHECKBUTTON_COL1 = FL_COL1
FL_CHECKBUTTON_COL2 = FL_YELLOW
FL_CHECKBUTTON_LCOL = FL_LCOL
FL_CHECKBUTTON_ALIGN = FL_ALIGN_CENTER

FL_CHECKBUTTON_TOPCOL = FL_COL1
FL_CHECKBUTTON_MCOL = FL_MCOL

# bitmap button defaults
FL_BITMAPBUTTON_BOXTYPE = FL_UP_BOX
FL_BITMAPBUTTON_COL1 = FL_COL1         # bitmap background
FL_BITMAPBUTTON_COL2 = FL_BLUE         # "focus" color
FL_BITMAPBUTTON_LCOL = FL_LCOL         # bitmap foreground
FL_BITMAPBUTTON_ALIGN = FL_ALIGN_BOTTOM

# bitmap button defaults
FL_PIXMAPBUTTON_BOXTYPE = FL_UP_BOX
FL_PIXMAPBUTTON_COL1 = FL_BUTTON_COL1
FL_PIXMAPBUTTON_COL2 = FL_BUTTON_COL2
FL_PIXMAPBUTTON_LCOL = FL_BUTTON_LCOL
FL_PIXMAPBUTTON_MCOL1 = FL_BUTTON_MCOL1
FL_PIXMAPBUTTON_MCOL2 = FL_BUTTON_MCOL2
FL_PIXMAPBUTTON_ALIGN = FL_ALIGN_BOTTOM


#######################
# forms.h (canvas.h)
# Header for FL_CANVAS
#######################

# values for enumeration 'FL_CANVAS_TYPE'
FL_NORMAL_CANVAS = 0
FL_SCROLLED_CANVAS = 1

# Default
FL_CANVAS_BOXTYPE = FL_DOWN_BOX     # really the decoration frame
FL_CANVAS_ALIGN = FL_ALIGN_TOP


#############################
# forms.h (chart.h)
# Object Class: Chart
#############################

# values for enumeration 'FL_CHART_TYPE'
FL_BAR_CHART = 0
FL_HORBAR_CHART = 1
FL_LINE_CHART = 2
FL_FILL_CHART = 3
FL_SPIKE_CHART = 4
FL_PIE_CHART = 5
FL_SPECIALPIE_CHART = 6

FL_FILLED_CHART = FL_FILL_CHART     # compatibility

# Defaults
FL_CHART_BOXTYPE = FL_BORDER_BOX
FL_CHART_COL1 = FL_COL1
FL_CHART_LCOL = FL_LCOL
FL_CHART_ALIGN = FL_ALIGN_BOTTOM

# Others
FL_CHART_MAX = 2048


#####################
# forms.h (choice.h)
#####################

# values for enumeration 'FL_CHOICE_TYPE'
FL_NORMAL_CHOICE = 0
FL_NORMAL_CHOICE2 = 1
FL_DROPLIST_CHOICE = 2
FL_BROWSER_CHOICE = 3

FL_SIMPLE_CHOICE = FL_NORMAL_CHOICE

# Defaults
FL_CHOICE_BOXTYPE = FL_ROUNDED_BOX
FL_CHOICE_COL1 = FL_COL1
FL_CHOICE_COL2 = FL_LCOL
FL_CHOICE_LCOL = FL_LCOL
FL_CHOICE_ALIGN = FL_ALIGN_LEFT

# Others
FL_CHOICE_MCOL = FL_MCOL
FL_CHOICE_MAXITEMS = 128


#################################
# forms.h (clock.h)
#################################

# values for unnamed enumeration
FL_ANALOG_CLOCK = 0
FL_DIGITAL_CLOCK = 1

FL_CLOCK_BOXTYPE = FL_UP_BOX
FL_CLOCK_COL1 = FL_INACTIVE_COL
FL_CLOCK_COL2 = FL_BOTTOM_BCOL
FL_CLOCK_LCOL = FL_BLACK
FL_CLOCK_ALIGN = FL_ALIGN_BOTTOM

FL_CLOCK_TOPCOL = FL_COL1


######################
# forms.h (counter.h)
######################

# values for enumeration 'FL_COUNTER_TYPE'
FL_NORMAL_COUNTER = 0
FL_SIMPLE_COUNTER = 1

# Defaults
FL_COUNTER_BOXTYPE = FL_UP_BOX
FL_COUNTER_COL1 = FL_COL1
FL_COUNTER_COL2 = FL_BLUE           # ct label
FL_COUNTER_LCOL = FL_LCOL           # ct reporting
FL_COUNTER_ALIGN = FL_ALIGN_BOTTOM

# Others
FL_COUNTER_BW = (FL_BOUND_WIDTH - 1)


#############################
# forms.h (cursor.h)
# Cursor defs and prototypes
#############################

# *** start - from /usr/include/cursorfont.h ***
XC_num_glyphs = 154
XC_X_cursor = 0
XC_arrow = 2
XC_based_arrow_down = 4
XC_based_arrow_up = 6
XC_boat = 8
XC_bogosity = 10
XC_bottom_left_corner = 12
XC_bottom_right_corner = 14
XC_bottom_side = 16
XC_bottom_tee = 18
XC_box_spiral = 20
XC_center_ptr = 22
XC_circle = 24
XC_clock = 26
XC_coffee_mug = 28
XC_cross = 30
XC_cross_reverse = 32
XC_crosshair = 34
XC_diamond_cross = 36
XC_dot = 38
XC_dotbox = 40
XC_double_arrow = 42
XC_draft_large = 44
XC_draft_small = 46
XC_draped_box = 48
XC_fleur = 52
XC_gobbler = 54
XC_gumby = 56
XC_hand1 = 58
XC_hand2 = 60
XC_heart = 62
XC_icon = 64
XC_iron_cross = 66
XC_left_ptr = 68
XC_left_side = 70
XC_left_tee = 72
XC_leftbutton = 74
XC_ll_angle = 76
XC_lr_angle = 78
XC_man = 80
XC_middlebutton = 82
XC_mouse = 84
XC_pencil = 86
XC_pirate = 88
XC_plus = 90
XC_question_arrow = 92
XC_right_ptr = 94
XC_right_side = 96
XC_right_tee = 98
XC_rightbutton = 100
XC_rtl_logo = 102
XC_sailboat = 104
XC_sb_down_arrow = 106
XC_sb_h_double_arrow = 108
XC_sb_left_arrow = 110
XC_sb_right_arrow = 112
XC_sb_up_arrow = 114
XC_sb_v_double_arrow = 116
XC_shuttle = 118
XC_sizing = 120
XC_spider = 122
XC_spraycan = 124
XC_star = 126
XC_target = 128
XC_tcross = 130
XC_top_left_arrow = 132
XC_top_left_corner = 134
XC_top_right_corner = 136
XC_top_side = 138
XC_top_tee = 140
XC_trek = 142
XC_ul_angle = 144
XC_umbrella = 146
XC_ur_angle = 148
XC_watch = 150
XC_xterm = 152
# *** end - from /usr/include/cursorfont.h ***

# values for unnamed enumeration
FL_INVISIBLE_CURSOR = -2
FL_DEFAULT_CURSOR = -1
FL_BUSY_CURSOR = XC_watch
FL_CROSSHAIR_CURSOR = XC_tcross
FL_KILL_CURSOR = XC_pirate
FL_NWARROW_CURSOR = XC_top_left_arrow
FL_NEARROW_CURSOR = XC_arrow

XC_invisible = FL_INVISIBLE_CURSOR


###################
# forms.h (dial.h)
###################

# values for enumeration 'FL_DIAL_TYPE'
FL_NORMAL_DIAL = 0
FL_LINE_DIAL = 1
FL_FILL_DIAL = 2

# values for unnamed enumeration
FL_DIAL_CW = 0
FL_DIAL_CCW = 1

# Defaults
FL_DIAL_BOXTYPE = FL_FLAT_BOX
FL_DIAL_COL1 = FL_COL1
FL_DIAL_COL2 = FL_RIGHT_BCOL
FL_DIAL_LCOL = FL_LCOL
FL_DIAL_ALIGN = FL_ALIGN_BOTTOM

# Others
FL_DIAL_TOPCOL = FL_COL1


############################################
# forms.h (filesys.h)
# Convenience functions to read a directory
############################################

# File types
# values for unnamed enumeration
FT_FILE = 0
FT_DIR = 1
FT_LINK = 2
FT_SOCK = 3
FT_FIFO = 4
FT_BLK = 5
FT_CHR = 6
FT_OTHER = 7

# values for unnamed enumeration
FL_ALPHASORT = 1            # sort in alphabetic order
FL_RALPHASORT = 2           # sort in reverse alphabetic order
FL_MTIMESORT = 3            # sort according to modifcation time
FL_RMTIMESORT = 4           # sort in reverse modificaiton time
FL_SIZESORT = 5             # sort in increasing size order
FL_RSIZESORT = 6            # sort in decreasing size order
FL_CASEALPHASORT = 7        # sort case insensitive
FL_RCASEALPHASORT = 8       # sort case insensitive


###################
# forms.h (flps.h)
###################

# postscript stuff
# values for unnamed enumeration
FLPS_AUTO = 0              # switch to landscale if does not fit
FLPS_LANDSCAPE = 1         # landscape always
FLPS_PORTRAIT = 2          # portrait always
FLPS_BESTFIT = 3           # even margins/best fit

# values for unnamed enumeration
FLPS_BW = -1
FLPS_GRAYSCALE = 0
FLPS_COLOR = 1


#########################
# forms. (formbrowser.h)
#########################

# values for unnamed enumeration
FL_NORMAL_FORMBROWSER = 0

# values for unnamed enumeration
FL_SMOOTH_SCROLL = 0
FL_JUMP_SCROLL = 1

FL_FORMBROWSER_BOXTYPE = FL_DOWN_BOX
FL_FORMBROWSER_COL1 = FL_COL1
FL_FORMBROWSER_ALIGN = FL_ALIGN_TOP


####################
# forms.h (frame.h)
####################

# types of frames
# values for unnamed enumeration
FL_NO_FRAME = 0
FL_UP_FRAME = 1
FL_DOWN_FRAME = 2
FL_BORDER_FRAME = 3
FL_SHADOW_FRAME = 4
FL_ENGRAVED_FRAME = 5
FL_ROUNDED_FRAME = 6
FL_EMBOSSED_FRAME = 7
FL_OVAL_FRAME = 8

FL_FRAME_COL1 = FL_BLACK        # border color
FL_FRAME_COL2 = FL_COL1         # label background
FL_FRAME_LCOL = FL_BLACK        # label color



#####################
# forms.h (free.h)
# Object Class: Free
#####################

# values for enumeration 'FL_FREE_TYPE'
FL_NORMAL_FREE = 0
FL_INACTIVE_FREE = 1
FL_INPUT_FREE = 2
FL_CONTINUOUS_FREE = 3
FL_ALL_FREE = 4

FL_SLEEPING_FREE = FL_INACTIVE_FREE


######################
# forms.h (goodies.h)
######################

# Resources and misc. goodie routines

FLAlertDismissLabel = "flAlert.dismiss.label"
FLAlertTitle = "flAlert.title"

FLQuestionYesLabel = "flQuestion.yes.label"
FLQuestionNoLabel = "flQuestion.no.label"
FLQuestionTitle = "flQuestion.title"

FLOKLabel = "flInput.ok.label"
FLInputClearLabel = "flInput.clear.label"
FLInputCancelLabel = "flInput.cancel.label"
FLInputTitle = "flInput.title"

FLChoiceTitle = "flChoice.title"


# file selector

FL_MAX_FSELECTOR = 6


####################
# forms.h (input.h)
####################

# Types
# values for enumeration 'FL_INPUT_TYPE'
FL_NORMAL_INPUT = 0
FL_FLOAT_INPUT = 1
FL_INT_INPUT = 2
FL_DATE_INPUT = 3
FL_MULTILINE_INPUT = 4
FL_HIDDEN_INPUT = 5
FL_SECRET_INPUT = 6

# for date input
# values for unnamed enumeration
FL_INPUT_MMDD = 0
FL_INPUT_DDMM = 1

# Defaults
FL_INPUT_BOXTYPE = FL_DOWN_BOX
FL_INPUT_COL1 = FL_COL1
FL_INPUT_COL2 = FL_MCOL
FL_INPUT_LCOL = FL_LCOL
FL_INPUT_ALIGN = FL_ALIGN_LEFT

# Others
FL_INPUT_TCOL = FL_LCOL
FL_INPUT_CCOL = FL_BLUE

FL_RINGBELL = (1<<4)


#####################
# forms.h (menu.h)
# Object Class: Menu
#####################

# values for enumeration 'FL_MENU_TYPE'
FL_TOUCH_MENU = 0
FL_PUSH_MENU = 1
FL_PULLDOWN_MENU = 2

# Defaults
FL_MENU_BOXTYPE = FL_BORDER_BOX
FL_MENU_COL1 = FL_COL1
FL_MENU_COL2 = FL_MCOL
FL_MENU_LCOL = FL_LCOL
FL_MENU_ALIGN = FL_ALIGN_CENTER

# Others
FL_MENU_MAXITEMS = 128
FL_MENU_MAXSTR = 64        # not used anymore! JTT


##############################################
# forms.h (menubar.h)
# Object Class: MenuBar
# THIS FILE SEEMS NOT TO BE NEEDED AT ALL JTT
##############################################

# values for unnamed enumeration
FL_NORMAL_MENUBAR = 0

# Defaults
FL_MENUBAR_BOXTYPE = FL_UP_BOX
FL_MENUBAR_COL1 = FL_COL1
FL_MENUBAR_COL2 = FL_MCOL
FL_MENUBAR_LCOL = FL_LCOL


# Nmenu object types
# values for unnamed enumeration
FL_NORMAL_NMENU = 0
FL_NORMAL_TOUCH_NMENU = 1
FL_BUTTON_NMENU = 2
FL_BUTTON_TOUCH_NMENU = 3


#########################
# forms.h (positioner.h)
#########################

FL_NORMAL_POSITIONER = 0
FL_OVERLAY_POSITIONER = 1

# Defaults
FL_POSITIONER_BOXTYPE = FL_DOWN_BOX
FL_POSITIONER_COL1 = FL_COL1
FL_POSITIONER_COL2 = FL_RED
FL_POSITIONER_LCOL = FL_LCOL
FL_POSITIONER_ALIGN = FL_ALIGN_BOTTOM


# values for unnamed enumeration
FL_VERT_SCROLLBAR = 0
FL_HOR_SCROLLBAR = 1
FL_VERT_THIN_SCROLLBAR = 2
FL_HOR_THIN_SCROLLBAR = 3
FL_VERT_NICE_SCROLLBAR = 4
FL_HOR_NICE_SCROLLBAR = 5
FL_VERT_PLAIN_SCROLLBAR = 6
FL_HOR_PLAIN_SCROLLBAR = 7
FL_HOR_BASIC_SCROLLBAR = FL_HOR_PLAIN_SCROLLBAR
FL_VERT_BASIC_SCROLLBAR = FL_VERT_PLAIN_SCROLLBAR

# values for unnamed enumeration
FL_NORMAL_SCROLLBAR = 0
FL_THIN_SCROLLBAR = 1
FL_NICE_SCROLLBAR = 2
FL_PLAIN_SCROLLBAR = 3


#####################
# forms.h (select.h)
#####################

# Select object types
# values for unnamed enumeration
FL_NORMAL_SELECT = 0
FL_MENU_SELECT = 1
FL_DROPLIST_SELECT = 2

# Defaults
FL_SELECT_COL1 = FL_COL1
FL_SELECT_COL2 = FL_MCOL
FL_SELECT_LCOL = FL_LCOL
FL_SELECT_ALIGN = FL_ALIGN_LEFT



#######################
# forms.h (slider.h)
# Object Class: Slider
#######################

FL_HOR_FLAG = 1
FL_SCROLL_FLAG = 8

# values for enumeration 'FL_SLIDER_TYPE'
FL_VERT_SLIDER = 0
FL_HOR_SLIDER = FL_VERT_SLIDER | FL_HOR_FLAG
FL_VERT_FILL_SLIDER = 2
FL_HOR_FILL_SLIDER = FL_VERT_FILL_SLIDER | FL_HOR_FLAG
FL_VERT_NICE_SLIDER = 4
FL_HOR_NICE_SLIDER = FL_VERT_NICE_SLIDER | FL_HOR_FLAG
FL_VERT_BROWSER_SLIDER = 6
FL_HOR_BROWSER_SLIDER = FL_VERT_BROWSER_SLIDER | FL_HOR_FLAG
# The following are for use with scrollbars only!
# for FL_VERT_SCROLLBAR and FL_HOR_SCROLLBAR
FL_VERT_BROWSER_SLIDER2 = FL_VERT_SLIDER | FL_SCROLL_FLAG
FL_HOR_BROWSER_SLIDER2 = FL_HOR_SLIDER | FL_SCROLL_FLAG
# for FL_VERT_THIN_SCROLLBAR and FL_VERT_THIN_SCROLLBAR
FL_VERT_THIN_SLIDER = FL_VERT_FILL_SLIDER | FL_SCROLL_FLAG
FL_HOR_THIN_SLIDER = FL_HOR_FILL_SLIDER | FL_SCROLL_FLAG
# for FL_VERT_NICE_SCROLLBAR and FL_HOR_NICE_SCROLLBAR
FL_VERT_THIN_SLIDER = FL_VERT_FILL_SLIDER | FL_SCROLL_FLAG
FL_HOR_THIN_SLIDER = FL_HOR_FILL_SLIDER | FL_SCROLL_FLAG
# for FL_VERT_NICE_SCROLLBAR and FL_HOR_NICE_SCROLLBAR
FL_VERT_NICE_SLIDER2 = FL_VERT_NICE_SLIDER | FL_SCROLL_FLAG
FL_HOR_NICE_SLIDER2 = FL_HOR_NICE_SLIDER | FL_SCROLL_FLAG
# for use as FL_VERT_PLAIN_SCROLLBAR and FL_VERT_PLAIN_SCROLLBAR
FL_VERT_BASIC_SLIDER = FL_VERT_BROWSER_SLIDER | FL_SCROLL_FLAG
FL_HOR_BASIC_SLIDER = FL_HOR_BROWSER_SLIDER | FL_SCROLL_FLAG

# Defaults
FL_SLIDER_BW1 = FL_BOUND_WIDTH
FL_SLIDER_BW2 = FL_BOUND_WIDTH - 1          #FL_abs(FL_BOUND_WIDTH) - 1
FL_SLIDER_BOXTYPE = FL_DOWN_BOX
FL_SLIDER_COL1 = FL_COL1
FL_SLIDER_COL2 = FL_COL1
FL_SLIDER_LCOL = FL_LCOL
FL_SLIDER_ALIGN = FL_ALIGN_BOTTOM

# Others
FL_SLIDER_FINE = 0.25
FL_SLIDER_WIDTH = 0.10


# values for enumeration 'FL_SPINNER_TYPE'
FL_INT_SPINNER = 0
FL_FLOAT_SPINNER = 1


########################
# forms.h (tabfolder.h)
########################

# values for unnamed enumeration
FL_TOP_TABFOLDER = 0        # tab on top
FL_BOTTOM_TABFOLDER = 1
FL_LEFT_TABFOLDER = 2
FL_RIGHT_TABFOLDER = 3
FL_NORMAL_TABFOLDER = FL_TOP_TABFOLDER

# values for unnamed enumeration
FL_NO = 0
FL_FIT = 1
FL_ENLARGE_ONLY = 2


###################
# forms.h (text.h)
###################

# values for unnamed enumeration
FL_NORMAL_TEXT = 0

FL_TEXT_BOXTYPE = FL_FLAT_BOX
FL_TEXT_COL1 = FL_COL1
FL_TEXT_COL2 = FL_MCOL
FL_TEXT_LCOL = FL_LCOL
FL_TEXT_ALIGN = FL_ALIGN_LEFT


#########################
# forms.h (thumbwheel.h)
#########################

# values for unnamed enumeration
FL_VERT_THUMBWHEEL = 0
FL_HOR_THUMBWHEEL = 1

# defaults
FL_THUMBWHEEL_COL1 = FL_COL1
FL_THUMBWHEEL_COL2 = FL_COL1
FL_THUMBWHEEL_LCOL = FL_BLACK
FL_THUMBWHEEL_BOXTYPE = FL_BORDER_BOX
FL_THUMBWHEEL_ALIGN = FL_ALIGN_BOTTOM


######################
# forms.h (timer.h)
# Object Class: Timer
######################

# values for enumeration 'FL_TIMER_TYPE'
FL_NORMAL_TIMER = 0
FL_VALUE_TIMER = 1
FL_HIDDEN_TIMER = 2

# Defaults
FL_TIMER_BOXTYPE = FL_DOWN_BOX
FL_TIMER_COL1 = FL_COL1
FL_TIMER_COL2 = FL_RED
FL_TIMER_LCOL = FL_LCOL
FL_TIMER_ALIGN = FL_ALIGN_CENTER

# Others
FL_TIMER_BLINKRATE = 0.2


###############################
# forms.h (xpopup.h)
# Prototypes for xpop-up menus
###############################

FL_MAXPUPI = 128    # max item each pup
FL_PUP_PADH = 4     # space between each items


# Class FL_XYPLOT
# values for enumeration 'FL_XYPLOT_TYPE'
FL_NORMAL_XYPLOT = 0    # solid line
FL_SQUARE_XYPLOT = 1    # with added square
FL_CIRCLE_XYPLOT = 2    # with added circle
FL_FILL_XYPLOT = 3      # fill completely
FL_POINTS_XYPLOT = 4    # only data points
FL_DASHED_XYPLOT = 5    # dashed line
FL_IMPULSE_XYPLOT = 6
FL_ACTIVE_XYPLOT = 7    # accepts interactive manipulations
FL_EMPTY_XYPLOT = 8
FL_DOTTED_XYPLOT = 9
FL_DOTDASHED_XYPLOT = 10
FL_LONGDASHED_XYPLOT = 11
FL_LINEPOINTS_XYPLOT = 12   # line & points

# values for unnamed enumeration
FL_LINEAR = 0
FL_LOG = 1

# values for unnamed enumeration
FL_GRID_NONE  = 0
FL_GRID_MAJOR = 1
FL_GRID_MINOR = 2

# Defaults
FL_XYPLOT_BOXTYPE = FL_FLAT_BOX
FL_XYPLOT_COL1 = FL_COL1
FL_XYPLOT_LCOL = FL_LCOL
FL_XYPLOT_ALIGN = FL_ALIGN_BOTTOM
FL_MAX_XYPLOTOVERLAY = 32


FL_FALSE = 0
FL_TRUE = (not FL_FALSE)


#########################
# flimage.h
# Image related routines
#########################

# values for unnamed enumeration
FL_IMAGE_NONE = 0
FL_IMAGE_MONO = 1           # b&w. 1bit. 0=white 1=black
FL_IMAGE_GRAY = 2           # 8 bit gray image
FL_IMAGE_CI = 4             # colormmaped image
FL_IMAGE_RGB = 8            # RGBA image. 8bit each
FL_IMAGE_PACKED = 16        # RGBA packed into an int
FL_IMAGE_GRAY16 = 32        # 12bit gray scale image
FL_IMAGE_RGB16 = 64         # 36bits color image
FL_IMAGE_FLEX = 1023        # all formats
# aliases
FLIMAGE_NONE = FL_IMAGE_NONE
FLIMAGE_MONO = FL_IMAGE_MONO
FLIMAGE_GRAY = FL_IMAGE_GRAY
FLIMAGE_CI = FL_IMAGE_CI
FLIMAGE_RGB = FL_IMAGE_RGB
FLIMAGE_PACKED = FL_IMAGE_PACKED
FLIMAGE_GRAY16 = FL_IMAGE_GRAY16
FLIMAGE_RGB16 = FL_IMAGE_RGB16
FLIMAGE_FLEX = FL_IMAGE_FLEX

FL_PCBITS = 8               # primary color bits
FL_PCMAX = (1 << FL_PCBITS) - 1

FL_RMASK = 0x000000ff
FL_RSHIFT = 0
FL_GMASK = 0x0000ff00
FL_GSHIFT = 8
FL_BMASK = 0x00ff0000
FL_BSHIFT = 16
FL_AMASK = 0xff000000
FL_ASHIFT = 24

FL_LUTBITS = 12         # max colormap bits. 4096 entries


# values for unnamed enumeration
FLIMAGE_AUTOCOLOR = 0x7fffffff
FLIMAGE_BADCOLOR = FLIMAGE_AUTOCOLOR


FLIMAGE_REPFREQ = 0x1f   # report every 32 lines


# possible errors from the library. Not currently (v0.89) used
# values for unnamed enumeration
FLIMAGE_ERR_NONE = 0
FLIMAGE_ERR_ALLOC = -50         # allocation error
FLIMAGE_ERR_INVALID = -49       # invalid image
FLIMAGE_ERR_ARGUMENT = -48      # bad argument/request
FLIMAGE_ERR_FILE = -47          # io error
FLIMAGE_ERR_INTERNAL = -46      # bugs
FLIMAGE_ERR_UNKNOWN = -45


# values for unnamed enumeration
FLIMAGE_WRITABLE = FL_WRITE
FLIMAGE_READABLE = FL_READ


# values for unnamed enumeration
FLIMAGE_NOSUBPIXEL = 0      # scale with no subpixel sampling
FLIMAGE_SUBPIXEL = 1        # scale with  subpixel sampling
FLIMAGE_CENTER = 2          # center warped image. default
FLIMAGE_RIGHT = 8           # flush right the warped image
FLIMAGE_ASPECT = 32         # fit the size
FLIMAGE_NOCENTER = FL_ALIGN_LEFT_TOP

